#!/usr/bin/env python

import sys

filename = sys.argv[1]+"/Info.plist"

f = open(filename, "r")
data = f.read()
if not "CFBundleURLSchemes" in data:
	f.close();
	lines = data.rsplit("\n")
	while lines.pop() != "</dict>":
		pass
	restdata = "\n".join(lines)
	restdata += '''<key>CFBundleURLTypes</key>
		<array>
			<dict>
				<key>CFBundleURLSchemes</key>
				<array>
					<string>fb[YOUR APP ID]</string>
				</array>
			</dict>
		</array>
	</dict>
	</plist>'''
	f = open(filename, "w")
	f.write(restdata)
	f.close()
